-- MySQL Script generated by MySQL Workbench
-- 09/09/14 11:21:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema problemdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `problemdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `problemdb` ;

-- -----------------------------------------------------
-- Table `problemdb`.`discipline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `problemdb`.`discipline` ;

CREATE TABLE IF NOT EXISTS `problemdb`.`discipline` (
  `iddiscipline` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`iddiscipline`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `problemdb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `problemdb`.`category` ;

CREATE TABLE IF NOT EXISTS `problemdb`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `iddiscipline` INT NOT NULL,
  `idparentcategory` INT NULL,
  PRIMARY KEY (`idcategory`),
  INDEX `fk_category_discipline_idx` (`iddiscipline` ASC),
  INDEX `fk_category_category1_idx` (`idparentcategory` ASC),
  CONSTRAINT `fk_category_discipline`
    FOREIGN KEY (`iddiscipline`)
    REFERENCES `problemdb`.`discipline` (`iddiscipline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`idparentcategory`)
    REFERENCES `problemdb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `problemdb`.`problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `problemdb`.`problem` ;

CREATE TABLE IF NOT EXISTS `problemdb`.`problem` (
  `idproblem` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  `solution` BLOB NULL,
  `idcategory` INT NOT NULL,
  PRIMARY KEY (`idproblem`),
  INDEX `fk_problem_category1_idx` (`idcategory` ASC),
  CONSTRAINT `fk_problem_category1`
    FOREIGN KEY (`idcategory`)
    REFERENCES `problemdb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
